version: '2'
services:

  db:
    image: postgres
  app:
    build: .
    command:
      - cd rails && ./bin/setup
      - foreman start -f Procfile.local
    ports:
      - "3000:3000"
    volumes:
      - $PWD:/app
      - app-data:/root
    working_dir: /app
    depends_on:
      - db

volumes:
  app-data:
  db-data:
