version: '2'
services:

  db:
    image: postgres
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - $PWD:/app
      - app-data:/root
      - bundle-data:/usr/local/bundle
    working_dir: /app
    depends_on:
      - db

volumes:
  app-data:
  bundle-data:
  db-data:
